### ISSUE TITLE
Create a clear white design for the weather component similar to the menu

### ISSUE THREAD

**Issue by Alexever17** [chingu-voyages/v8-geckos-team-14#20]

**Comment by fabianstarke** [comment]
@Alexever17  I am not sure about this one ! Why should we have all in light colors ! I personnaly prefer dark and as developers are our target I think they mostly use dark themes Or maybe we should add a toggle to change theme in our app ? Let me know what you think

**Comment by Alexever17** [comment]
We may need to overhaul our design philosophy in general
But bright and dark mode sounds fun
